export default {
	// FONT
	FONT_SIZE_EXTRA_SMALL: 12,
	FONT_SIZE_SMALL: 14,
	FONT_SIZE_NORMAL: 16,
	FONT_SIZE_MEDIUM: 18,
	FONT_SIZE_LARGE: 20,

	// FONT FAMILY
	FONG_FAMILY: null,

	// COLORS
	PRIMARY_COLOR: '#63004F',
	SECONDARY_COLOR: '#63004f',
	WHITE_COLOR: '#FFFFFF',
	BLACK_COLOR: '#000000',
	DARK_COLOR: '#000000',
	LIGHT_COLOR: '#8C8893',
	BACKGROUND_COLOR: '#00000010',

	// WEIGHT
	FONT_WEIGHT_LIGHT: '400',
	FONT_WEIGHT_MEDIUM: '700',
	FONT_WEIGHT_HEAVY: 'bold',

	// BORDER RADIUS
	IMAGE_BORDER_RADIUS: 5,
	BUTTON_BORDER_RADIUS: 5,
};